var  festival = [{
    nameLeHoi: 'lễ hội Dussehra',
    tiemStart:'2018/9/25',
    timeEnd:'2018/10/05',
    diadiem: 'Ấn Độ',
    kinhdo:'20.7689051',
    vido:'73.7301886',
    lucdia:'Châu Á',
    tongiao:'Đạo Hindu',
    chitiet:'Dussehra là một trong nhiều lễ hội phổ biến tổ chức của người Hindu trên toàn Ấn Độ với tên gọi khác nhau trong không khí tưng bừng và rực rỡ chiến thắng của Rama vào tháng Ashvin (khoảng tầm cuối tháng 9 – đầu tháng 10 hàng năm).  Lễ hội này còn được gọi là lễ hội Vijayadashmi.  “Vijay” có nghĩa là chiến thắng và “Dashmi” có nghĩa là ngày thứ mười. Lễ hội này cũng được hiểu là “Dasa-Hara” có nghĩa là cắt mười cái đầu của vua quỷ Ravana vua xứ Lanka. Theo truyền thuyết Người Ấn-Hindu tin rằng đó là vào ngày này Rama cùng với thần Lakshman và Khỉ vương Hanuma giết chết vua quỷ Ravana sau chín ngày đêm  chiến đấu giải cứu người vợ bị bắt cóc của mình – Sita vào ngày thứ mười. Họ trở về Ayodhya trong chiến thắng và vinh quang và tổ chức lễ hội mừng chiến thắng này. Nói cách khác, Lễ hội này là sự chiến thắng của cái thiện đối với cái ác. Chiến thắng của Rama vẫn còn được lưu truyền cho đến ngày nay .',
    url1:'imgs/Dussehra-hindu/Dussehra-431.jpg',
    url2:'imgs/Dussehra-hindu/Dussehra-432.jpg', 
    url3:'imgs/Dussehra-hindu/Dussehra-433.jpg', 
    url4:'imgs/Dussehra-hindu/Dussehra-hight1.jpg',
    url5:'imgs/Dussehra-hindu/Dussehra-hight2.jpg',
    url6:'imgs/Dussehra-hindu/Dussehra-hight3.png'
},
{
    nameLeHoi: 'lễ hội ánh sáng Diwali',
    tiemStart:'2018/10/29',
    timeEnd:'2018/11/2',
    diadiem: 'Ấn Độ',
    kinhdo:'20.7689051',
    vido:'73.7301886',
    lucdia:'Châu Á',
    tongiao:'Đạo Hindu',
    chitiet:'Diwali thường diễn ra vào cuối tháng 10 hoặc đầu tháng 11 dương lịch hàng năm tại Ấn Độ. Lễ hội diễn ra 5 ngày để chào đón một năm mới trong đạo Hindu và cũng thể hiện sức mạnh của chính nghĩa, đặc biệt là chiến thắng của anh hùng Lord Rama và nàng Sita-vợ anh trước những kẻ xấu. Giống như tết Nguyên đán ở Việt Nam, Diwali là lễ hội truyền thống lớn nhất ở Ấn Độ nên sinh viên các trường được nghỉ học 2 tuần để có nhiều thời gian chuẩn bị. Trong thời gian diễn ra lễ hội, Ấn Độ gần như không có đêm, ngoài pháo hoa, người dân còn đốt khá nhiều pháo sáng rực rỡ. Tất cả mọi người đều mặc quần áo mới, đặc biệt phụ nữ sẽ diện trang phục sari truyền thống, gặp gỡ vui chơi và thăm hỏi chúc tết lẫn nhau. Vào 17h ngày 27/10/2017, Lễ hội Ánh sáng truyền thống Ấn Độ sẽ được tổ chức tại Trung tâm Văn hóa Ấn Độ ở Hà Nội. Nếu có dịp đến đây vào ngày này, bạn sẽ được tham gia những hoạt động thú vị như mặc thử trang phục Sari truyền thống, xem nghệ thuật vẽ Henna, lễ thắp đèn, thưởng thức ca nhạc và nghệ thuật Diwali .',
    url1:'imgs/Diwali/diwali-431.jpg',
    url2:'imgs/Diwali/diwali-432.jpg', 
    url3:'imgs/Diwali/diwali-433.jpg', 
    url4:'imgs/Diwali/diwali-hight1.jpg',
    url5:'imgs/Diwali/diwali-hight2.jpg',
    url6:'imgs/Diwali/diwali-hight3.jpg'
},
{
    nameLeHoi: 'Lễ hội Ganesha',
    tiemStart:'2018/07/07',
    timeEnd:'2018/07/18',
    diadiem: 'Ấn Độ',
    kinhdo:'20.7689051',
    vido:'73.7301886',
    lucdia:'Châu Á',
    tongiao:'Đạo Hindu',
    chitiet:'Theo truyền thuyết Ganesha là con trai của thần Shiva và nữ thần Parvati. Nữ thần Parvati luôn bị thần Shiva nhìn với con mắt thèm muốn nên nữ thần đã tìm cách tự bảo vệ mình. Do đó bà đã tạo ra thần Ganesha khi Shiva đang trên đường đi săn. Khi Shiva đi săn trở về không nhận ra cơ thể nữ thần Parvati vì chúng được Ganesha che mất. Shiva rất tức tối và đã chặt đứt đầu Ganesha. Paravati cầu xin Shiva để Ganesha được sống và cho Ganesha một cái đầu mới. Để Paravati không đau khổ, Shiva đã ra lệnh chặt đầu con vật đầu tiên thần nhìn thấy gắn làm đầu cho Ganesha. Và con vật ấy là một con voi. Parvati người đã tạo nên hình hài của thần voi Ganesha (con trai của Shiva và Parvati) từ những phần nhơ nhuốc của cơ thể bà; sau này thần Ganesha đã được ban cho sự sống nhờ nước thánh của thần Ganga. Do đó, Ganesha được xem như có hai bà mẹ—Pārvati và Gangā, và cũng vì thế nên được gọi là Dvaimātura và Gāngeya (con trai của Ganga). Lễ hội Ganesh Chaturthi là một trong những lễ hội rất quan trọng của người Hindu (theo Ấn Độ giáo) ở Mumbai - người Ấn Độ kỷ niệm ngày sinh của thần Ganesha đầu voi. Hầu hết các giáo phái của đạo Hindu đều tôn thờ Ganesha. Ở phía nam Ấn Độ, Ganesha là thần chính. Nhiều ngày trước lễ hội tượng thần được dựng lên, vào ngày chính hội tượng thần và người dự hội được hóa trang sặc sỡ với màu chủ đạo là màu đỏ.Người tham gia lễ hội vui chơi, ca hát và nhảy múa. Ở Mumbai ngày hội này cũng là ngày nghỉ và họ chúc tụng nhau gặp nhiều may mắn, hạnh phúc .',
    url1:'imgs/Ganesha/ganesha-431.jpg', 
    url2:'imgs/Ganesha/ganesha-432.jpg',
    url3:'imgs/Ganesha/ganesha-433.jpg',
    url4:'imgs/Ganesha/ganesha-hight1.jpg',
    url5:'imgs/Ganesha/ganesha-hight2.jpg',
    url6:'imgs/Ganesha/ganesha-hight3.jpg'
},
{
    nameLeHoi: 'Lễ hội sắc màu Holi',
    tiemStart:'2018/03/16',
    timeEnd:'2018/3/27',
    diadiem: 'Ấn Độ',
    kinhdo:'20.7689051',
    vido:'73.7301886',
    lucdia:'Châu Á',
    tongiao:'Đạo Hindu',
    chitiet:'Holi là lễ hội đặc sắc của cộng đồng người Hindu được tổ chức hàng năm vào khoảng giữa tháng 3, đánh dấu sự kết thúc của mùa đông, khởi đầu của vụ mùa bội thu sắp tới. Theo truyền thống, những người tham gia lễ hội Holi sẽ ném bột màu hoặc pha bột màu với nước và ném vào nhau, thể hiện sự tự do và không phân biệt giai cấp vốn tồn tại trong xã hội. Ai nhận được nhiều màu thì sẽ có nhiều may mắn trong năm .',
    url1:'imgs/holi-hindu/holi-431.jpg',
    url2:'imgs/holi-hindu/holi-432.jpg',
    url3:'imgs/holi-hindu/holi-433.jpg',
    url4:'imgs/holi-hindu/holi-hight1.jpg',
    url5:'imgs/holi-hindu/holi-hight2.jpg',
    url6:'imgs/holi-hindu/holi-hight3.jpg'
},
{
    nameLeHoi: 'lễ hội Navratri',
    tiemStart:'2018/03/05',
    timeEnd:'2018/03/14',
    diadiem: 'Ấn Độ',
    kinhdo:'20.7689051',
    vido:'73.7301886',
    lucdia:'Châu Á',
    tongiao:'Đạo Hindu',
    chitiet:'Lễ hội Navratri được tổ chức trong 9 ngày để thờ 9 hình thái khác nhau của nữ thần Durga. Đối với người Ấn Độ theo đạo Hindu, nữ thần Durga được xem là thiên mẫu, mẹ của vũ trụ. Mỗi năm, người dân Ấn tổ chức lễ Navratri vào 2 dịp quan trọng là mùa xuân và mùa thu hoạch. Vào dịp lễ Navratri, các bé gái 9 tuổi trong gia đình sẽ được tôn thờ như nữ thần và được tặng nhiều món quà bởi người Ấn cho rằng các bé gái 9 tuổi hội đủ sức mạnh và năng lượng tinh khiết giống như nữ thần Durga. Ở một số nơi, tượng của nữ thần Durga được đắm mình trong những con sông thiêng liêng vào ngày thứ 10 .',
    url1:'imgs/Navratri-hindu/navratri-431.jpg',
    url2:'imgs/Navratri-hindu/navratri-432.jpg',
    url3:'imgs/Navratri-hindu/navratri-433.jpg', 
    url4:'imgs/Navratri-hindu/navratri-hight1.jpg',
    url5:'imgs/Navratri-hindu/navratri-hight2.jpg',
    url6:'imgs/Navratri-hindu/navratri-hight3.jpg'
},
{
    nameLeHoi: 'Lễ hội Shivaratri',
    tiemStart:'2018/02/26',
    timeEnd:'2018/02/27',
    diadiem: 'Ấn Độ',
    kinhdo:'20.7689051',
    vido:'73.7301886',
    lucdia:'Châu Á',
    tongiao:'Đạo Hindu',
    chitiet:'Shivaratri cũng là một lễ hội quan trọng của cộng đồng Hindu giáo được tổ chức để tôn thờ thần Shiva- chúa tể của sự hủy diệt. Lễ hội Shivaratri bắt đầu vào đêm ngày 13 và kéo dài hết ngày 14 của tháng Maagha theo lịch Hindu (tức là khoảng tháng 2, tháng 3 dương lịch). Những tín đồ Hindu tập trung ở các đền thờ thần Shiva và thức suốt đêm để thực hiện nghi lễ truyền thống bên biểu tượng linga của thần Shiva. Nhiều người cũng hóa trang và mặc những bộ trang phục ma vào dịp lễ hội này .',
    url1:'imgs/Shivaratri-hindu/shivaratri-431.jpg',
    url2:'imgs/Shivaratri-hindu/shivaratri-432.jpg',
    url3:'imgs/Shivaratri-hindu/shivaratri-433.jpg',
    url4:'imgs/Shivaratri-hindu/shivaratri-hight1.jpg',
    url5:'imgs/Shivaratri-hindu/shivaratri-hight2.jpg',
    url6:'imgs/Shivaratri-hindu/shivaratri-hight3.jpg'
},
{
    nameLeHoi: 'Lễ hội Janmashtami',
    tiemStart:'2018/09/02',
    timeEnd:'2018/09/02',
    diadiem: 'Ấn Độ',
    kinhdo:'20.7689051',
    vido:'73.7301886',
    lucdia:'Châu Á',
    tongiao:'Đạo Hindu',
    chitiet:'Ngày 22/08/2011 vừa qua, người theo Đạo Hindu đã tưng bừng tổ chức ngày lễ Janmashtami, kỷ niệm ngày sinh của thần Krishna, tại Ấn Độ, Bangladesh và Anh. Krishna, một trong tám hóa thân của thần Vishnu, là hiện thân của tình yêu, là sự hủy diệt cho đau khổ và tội lỗi, là người cai quản và bảo vệ âm thanh của loài bò, là sự kết nối tình yêu của con người với Thượng đế, là đại diện cho kiến thức. Trong lễ Janmashtami, trẻ em và người lớn sẽ mặc những bộ trang phục như của thần Krishna và người vợ là Radha, với gam màu sáng, trang trí công phu và nhiều đồ trang sức. Những tháp người sẽ được tạo nên để với tới chiếc bình “Dahi-Handi”. Chiếc bình này có chứa sữa, phomat, bơ, mật ong và trái cây, được treo ở độ cao từ 6 – 12m. Mọi người cùng hợp sức tạo thành một kim tự tháp người để giúp người ở vị trí cao nhất có thể chạm được chiếc bình và công bố những vật chứa trong bình đó. Lễ hội Janmashtami là một trong những lễ hội quan trọng nhất trong năm của người theo Đạo Hindu .',
    url1:'imgs/janmashtami-hindu/janmashtami-431.jpg', 
    url2:'imgs/janmashtami-hindu/janmashtami-432.jpg',
    url3:'imgs/janmashtami-hindu/janmashtami-433.jpg',
    url4:'imgs/janmashtami-hindu/janmashtami-hight1.jpg',
    url5:'imgs/janmashtami-hindu/janmashtami-hight2.jpg',
    url6:'imgs/janmashtami-hindu/janmashtami-hight3.jpg'
},
{
    nameLeHoi: 'Lễ hội Ugadi',
    tiemStart:'2018/02/16',
    timeEnd:'2018/02/16',
    diadiem: 'Ấn Độ',
    kinhdo:'20.7689051',
    vido:'73.7301886',
    lucdia:'Châu Á',
    tongiao:'Đạo Hindu',
    chitiet:'Ngày lễ được chuẩn bị trước khoảng 1 tuần,dọn dẹp nhà cửa,mua sắm đồ dùng,vật dụng cho ngày lễ. Vào ngày lễ Ugadi,mọi người thức dậy lúc bình minh để tắm rử sau đó trang trí lối vào nhà với lá xoài tươi.Việc trang trí bằng lá xoài   liên quan đến một truyền thuyết:  Kartik (hoặc Subramanya hoặc Kumara Swamy) và Ganesha, hai người con của Shiva và Parvathi rất thích xoài, theo  truyền thuyết thì Kartik hô hào mọi người buộc lá xoài xanh vào cửa với ý nghĩa cầu mong năm mới  vụ mùa bội thu và mọi người có sức khỏe dồi dào. Mọi người cũng tưới nước phân bò tươi lên mặt đất  phía trước của ngôi nhà của họ, cầu nguyện cho sức khỏe, sự giàu có, thịnh vượng và thành công trong kinh doanh.Ugadi cũng là thời gian tốt đẹp nhất để bắt đầu các dự án mới. Trong ngày lễ  Ugadi,các món ăn đặc biệt được chuẩn bị Ở Andhra Pradesh và Telangana, các món ăn truyền thống như "pulihora, bobbatlu (Bhakshalu / polelu / oligalu) và Pachadi" cung với  các món ăn được chế biến từ xoài .',
    url1:'imgs/Ugadi-hindu/ugadi-431.jpg',
    url2:'imgs/Ugadi-hindu/ugadi-432.jpg',
    url3:'imgs/Ugadi-hindu/ugadi-433.jpg', 
    url4:'imgs/Ugadi-hindu/ugadi-hight1.jpg',
    url5:'imgs/Ugadi-hindu/ugadi-hight2.jpg',
    url6:'imgs/Ugadi-hindu/ugadi-hight3.jpg'
}
];