var  festival = [{
    nameLeHoi: 'Oktoberfest',
    timeStart:'2018/10/12',
    timeEnd:'2018/10/17',
    diadiem: 'Munich, Đức',
    kinhdo:'48.155004',
    vido:'11.4717964',
    lucdia:'Châu Âu',
    tongiao:'Không',
    chitiet:'Lễ hội Oktoberfest là lễ hội bia tháng 10 của người dân xứ  Bavvaria –Munich nước Đức. Lễ hội được tổ chức nhằm kỉ niệm lễ cưới hoàng thái tử Ludwig (sau này là vua Ludwig I) và công chúa Therese của Sachsen-Hildburghausen (vì thế mà có tên Theresienwiese-Cánh đồng Therese) đã tổ chức một cuộc đua ngựa lớn. Lễ cưới được tổ chức vào ngày 12 tháng 10, cuộc đua ngựa vào ngày 17 tháng 10, vì thế mà thời điểm được ghi lại khác nhau. Đây là lễ hội bia lớn nhất thế giới có lịch sử hơn 200 năm của người Đức, ước tính hàng năm có khoảng trên 6 triệu lượt khách từ khắp nơi trên thế giới đổ về tham dự  lễ hội và tiêu thụ khoảng hơn 7 triệu lít bia. Lễ hội tháng Mười được khai mạc bằng 12 phát súng chào và sau khi thị trưởng đương nhiệm đóng vòi khui thùng bia đầu tiên. Người thị trưởng đầu tiên khui thùng bia là Thomas Wimmer.  Đây là dịp để các hãng bia nổi tiếng xứ Bavaria quảng bá sản phẩm tốt nhất tới toàn thể du khách tham gia lễ hội. Mọi người đến lễ hội với trang phục truyền thống cùng uống bia, thưởng thức các món ăn truyền thống, cùng tham gia hát các bài hát dân ca Đức và các trò chơi trong lễ hội ( Ví dụ như: Thi uống bia, đu quay, kéo co, thi ăn xúc xích…) .',
    url1:'imgs/oktoberfest/lễ hội bia 341.jpg',
    url2:'imgs/oktoberfest/lễ hội bia 342.jpg', 
    url3:'imgs/oktoberfest/lễ hội bia 343.jpg', 
    url4:'imgs/oktoberfest/lehoibia-hight1.jpg',
    url5:'imgs/oktoberfest/lehoibiahight-2.jpg',
    url6:'img/oktoberfest/lehoibia-hight3.jpg'
},
{
    nameLeHoi: 'Lễ hội chanh',
    timeStart:'2018/02/15',
    timeEnd:'2018/3/3',
    diadiem: 'Menton, Pháp',
    kinhdo:'43.7763166',
    vido:'7.4958256',
    lucdia:'Châu Âu',
    tongiao:'Không',
    chitiet:'Đây là lễ hội thường niên được tổ chức ở thành phố Menton, nước Pháp vào giữa tháng 2 đến đầu tháng 3 hàng năm. Menton là một vùng khí hậu ôn hòa ở miền Nam nước Pháp, nổi tiếng với cảnh đẹp làng quê và là nơi trồng chanh lý tưởng nhất châu Âu. Sự kiện hoành tráng với chủ thể chính là trái chanh này xuất phát từ ý tưởng tuyệt vời của nhóm những người quản lý khách sạn nhằm thu hút khách du lịch đến với Menton. Họ đề nghị tổ chức cuộc triển lãm hoa và cây ăn quả có múi trong vườn khách sạn Riviera. Sự kiện đã tạo ấn tượng mạnh và thu hút được sự chú ý và hưởng hứng của người dân địa phương và đặc biệt là du khách. Từ đó, Lễ hội chanh chính thức ra đời. Gần 80 năm qua, lễ hội vẫn được tổ chức đều đặn. Mỗi năm, ban tổ chức lễ hội sẽ đưa ra một chủ đề và tác phẩm trưng bày trên đường phố sẽ được tạo hình theo các chủ đề đó. Các chủ đề trong các năm vừa qua là điện ảnh, rock & roll, các công trình kiến trúc nổi tiếng, các con vật... với sự góp mặt của rất nhiều chuyên gia và nghệ sỹ tạo hình. Các nghệ nhân sử dụng đến hàng trăm tấn cam và chanh để xây dựng các công trình độc đáo như đền Taj Maha, cối xay gió... trong các mùa lễ hội, thu hút hàng trăm ngàn lượt du khách từ mọi nơi trên thế giới ghé thăm ngay cả trong tiết trời mùa đông lạnh giá. Không chỉ có chanh, những quả cam đẹp nhất, với sắc màu rực rỡ cũng được sử dụng để tạo nên những tác phẩm mê hồn từ chanh.  Để hoàn thành những kiệt tác từ hoa quả này, những nghệ nhân của thành phố Menton đã phải chuẩn bị từ rất sớm trước đó, từ khâu chọn lựa cam, chanh chín tới trong vườn tới lên ý tưởng, thực hiện và hoàn thành ý tưởng. Có rất nhiều hình ảnh đẹp được diễn ra trong lễ hội, du khách đến đây vào đúng dịp lễ hội sẽ được tận mắt chứng kiến những kiệt tác từ chanh lộng lẫy và sáng loáng .',
    url1:'imgs/lễ hội chanh(pháp)/lehoichanh-431.jpg',
    url2:'imgs/lễ hội chanh(pháp)/lehoichanh-432.jpg', 
    url3:'imgs/lễ hội chanh(pháp)/lehoichanh-433.jpg', 
    url4:'imgs/lễ hội chanh(pháp)/lehoichanh-hight1.jpg',
    url5:'imgs/lễ hội chanh(pháp)/lehoichanh-hight2.jpg',
    url6:'imgs/lễ hội chanh(pháp)/lehoichanh-hight3.jpg'
},
{
    nameLeHoi: 'Lễ hội cõng vợ',
    timeStart:'2018/07/07',
    timeEnd:'2018/07/18',
    diadiem: 'Sonkajarvi, Phần Lan',
    kinhdo:'63.6716476',
    vido:'27.5133322',
    lucdia:'Châu Âu',
    tongiao:'Không',
    chitiet:' (PLO) -Cuộc thi diễn ra vào ngày thứ bảy đầu tiên của tháng 7, ở thành phố Sonkajarvi, phía bắc thủ đô Helsinki, Phần Lan. Trong dịp lễ hội, những người đàn ông sẽ cõng cô vợ hoặc người yêu của mình trên vai và vượt qua những chướng ngại vật trong thời gian ngắn nhất để giành chiến thắng. Điểm độc đáo của lễ hội này có lẽ là tính chất hài hước của nó. Trong thời gian diễn ra cuộc tranh tài giữa các cặp đôi, cả người tham gia và người xem đều cảm nhận được sự vui vẻ và hứng khởi mà không phải lễ hội nào cũng mang lại được. Lễ hội cõng vợ này dường như đã ăn sâu vào trong tiềm thức của người dân địa phương. Có rất nhiều giả thuyết về lễ hội hài hước này, theo đó, truyền thuyết kể lại rằng, vào thế kỷ thứ 19, có một tên cướp khét tiếng tên là Rosvo-Ronkainen sống trong rừng và thành lập một băng cướp. Vì muốn rèn luyện sức khỏe cho các thành viên trong băng đảng của mình, Ronkainen đã tổ chức một khóa học vô cùng khó khăn: Yêu cầu các thành viên phải đeo bao tải nặng hay những con thú rừng trên lưng, chạy thật nhanh để tăng cường năng lực bản thân về sự nhanh nhẹn, sức mạnh và sức chịu đựng cho họ. Trước khi lễ hội diễn ra, các cặp đôi có ý định tranh tài sẽ phải rèn luyện sức khỏe từ trước đó một cách nghiêm túc và chăm chỉ, đòi hỏi một tinh thần nỗ lực rất cao từ cả hai phía. Tham gia lễ hội này không phải chỉ có những thí sinh là người dân đất nước Phần Lan mà bất kỳ người dân của nước nào muốn tham gia cũng được phép đăng ký tham dự. Người ta thống kê, mỗi năm có các thí sinh đến từ 15 quốc gia khác nhau như Australia, Mỹ, Hong Kong, Nhật Bản... cùng đổ về tham gia vào lễ hội vui nhộn này .',
    url1:'imgs/lễ hội cõng vợ (phần lan)/congvo-431.jpg', 
    url2:'imgs/lễ hội cõng vợ (phần lan)/congvo-432.jpg',
    url3:'imgs/lễ hội cõng vợ (phần lan)/congvo-433.jpg',
    url4:'imgs/lễ hội cõng vợ (phần lan)/congvo-hight1.jpg',
    url5:'imgs/lễ hội cõng vợ (phần lan)/congvo-hight2.jpg',
    url6:'imgs/lễ hội cõng vợ (phần lan)/congvo-hight3.jpg'
},
{
    nameLeHoi: 'Lễ hội đấu bò tót',
    timeStart:'2018/09/23',
    timeEnd:'2018/10/22',
    diadiem: 'Pamplona, Tây Ban Nha',
    kinhdo:'42.8157961',
    vido:'-1.6675312',
    lucdia:'Châu Âu',
    tongiao:'Không',
    chitiet:'Đấu bò tót là một lễ hội truyền thống của Tây Ban Nha ở thành phố Pamplona. Hàng năm lại có rất nhiều du khách từ khắp mọi nơi không hẹn mà gặp tại đây để được tận mắt chứng kiến những trận đấu kịch tính của hiệp sĩ với những chú bò dũng mãnh. Nhưng có lẽ không phải tất cả những người đến xem đều hiểu rõ tường tận được từ đâu lại có cuộc đấu bò tót thú vị này. Trước đây, lễ hội kéo dài một tuần này được tổ chức vào tháng Mười hàng năm để tôn vinh vị thánh bảo hộ San Fermín của thành phố . Xuất xứ của nó có lẽ bắt nguồn từ thời Trung cổ. Sau đó, trải qua bao nhiêu thời gian, những người tham gia lễ hội dần dần đã cho thêm những hoạt động khác vào sự kiện này như hội chợ, ca nhạc, các cuộc thi nhào lộn, đua bò và đấu bò tót. Chính xác thì nó đã có tuổi đời khoảng 421 năm. Dù các sự kiện ăn mừng tôn vinh thánh bảo hộ đã bắt đầu có từ thế kỷ XIII nhưng lễ hội đấu bò mới chỉ được tổ chức thường niên từ năm 1592, một thế kỷ sau khi đế quốc Tây Ban Nha bắt đầu phong trào thám hiểm thế giới và Columbus phát hiện ra châu Mỹ. Cũng vào năm này, lễ hội đấu bò đã được chuyển sang tổ chức vào tháng Bảy thay vì tháng Mười như trước kia để hợp nhất với một lễ hội khác cũng trong tháng Bảy. Từ đó trở đi, sự kiện này đã trở thành tâm điểm cho mùa hè ở Tây Ban Nha .',
    url1:'imgs/lễ hội đấu bò (Tây Ban Nha)/lehoidaubo-431.jpg',
    url2:'imgs/lễ hội đấu bò (Tây Ban Nha)/lehoidaubo-432.jpg',
    url3:'imgs/lễ hội đấu bò (Tây Ban Nha)/lehoidaubo-433.jpg',
    url4:'imgs/lễ hội đấu bò (Tây Ban Nha)/lehoidaubo-hight1.jpg',
    url5:'imgs/lễ hội đấu bò (Tây Ban Nha)/lehoidaubo-hight2.jpg',
    url6:'imgs/lễ hội đấu bò (Tây Ban Nha)/lehoidaubo-hight3.jpg'
},
{
    nameLeHoi: 'Lễ hội hoa hồng',
    timeStart:'2018/06/05',
    timeEnd:'2018/06/12',
    diadiem: 'Kazanlak, Bulgaria',
    kinhdo:'42.625243',
    vido:'25.3960953',
    lucdia:'Châu Âu',
    tongiao:'Không',
    chitiet:'Lễ hội hoa hồng là lễ hội được tao ra nhằm chào mừng Quốc khánh nước Cộng hòa Bulgaria 3/3 và ngày Quốc tế Phụ nữ 8/3. lễ hội được tổ chức vào ngày Chủ nhật đầu tiên của tháng 6 hàng năm tại Kazanlak thung lũng trồng hoa hồng nổi tiếng nhất ở Bulgaria, hoa hồng ở Kazanlak được thu hoạch trong khoảng thời gian từ tháng 5 đến tháng 6 hàng năm. Trước thời gian diễn ra lễ hội hoa hồng, người dân ở Kazanlak sẽ tổ chức cuộc thi tuyển chọn Hoa hậu Hoa hồng – cuộc thi sắc đẹp quen thuộc và cũng rất đặc trưng ở đất nước Bulgaria. Việc đoạt được vương niệm này là giấc mơ của tất cả các cô gái ở Kazanlak. Để đoạt được danh hiệu Hoa hậu Hoa hồng, ngoài xinh đẹp, có trí tuệ các cô gái còn phải nắm vững những kiến thức và kỹ thuật trồng hoa hồng. Người đoạt ngôi vị hoa hậu sẽ ngồi trên xe hoa diễu hành trong lễ hội để gửi lời chúc phúc đến mọi người. Sau đó người dân và khách du lịch sẽ cùng nhau diễu hành trên đường phố với những lẵng hoa tươi thắm và nhảy những điệu múa dân gian rất đặc trưng của người dân địa phương .',
    url1:'imgs/lễ hội hoa hồng (Bulgaria)/lehoihoahong-431.jpg',
    url2:'imgs/lễ hội hoa hồng (Bulgaria)/lehoihoahong-432.jpg',
    url3:'imgs/lễ hội hoa hồng (Bulgaria)/lehoihoahong-433.jpg', 
    url4:'imgs/lễ hội hoa hồng (Bulgaria)/lehoihoahong-hight1.jpg',
    url5:'imgs/lễ hội hoa hồng (Bulgaria)/lehoihoahong-hight2.jpg',
    url6:'imgs/lễ hội hoa hồng (Bulgaria)/lehoihoahong-hight3.jpg'
},
{
    nameLeHoi: 'Lễ hội hóa trang venice',
    timeStart:'2018/02/13',
    timeEnd:'2018/02/27',
    diadiem: 'Venice, Ý',
    kinhdo:'45.4551712',
    vido:'12.251931',
    lucdia:'Châu Âu',
    tongiao:'Không',
    chitiet:'Được đánh giá là một trong những lễ hội mùa xuân hấp dẫn nhất thế giới, Lễ hội carnival hằng năm ở Venice, Italy luôn thu hút số lượng lớn du khách từ khắp nơi trên thế giới. Lễ hội hóa trang Venice lần đầu tiên được tổ chức vào năm 1296. Sau một thời gian khá dài gián đoạn, lễ hội được khôi phục vào năm 1980 và được tổ chức đều đặn hàng năm cho đến nay. Mỗi năm lễ hội mang một chủ đề khác nhau nhưng đều  nhằm tôn vinh văn hóa và tạo nên những ngày hội vui vẻ cho người dân đầu năm mới. Trong suốt thời gian hai tuần, quảng trường St. Mark, các rạp hát, đường phố và tòa nhà công sở trở thành sàn diễn của các diễn viên, người làm xiếc, vũ công, nhạc sĩ... khiến người ta có cảm giác như đang sống ở thế kỷ XVII. Mặt nạ là nét đặc trưng nhất của lễ hội hóa trang Venice. Những nghệ nhân làm mặt nạ cũng có vị trí riêng được tôn trọng trong xã hội, với những phường hội và luật lệ riêng của họ. Mặt nạ hóa trang thường được làm bằng da hoặc bằng giấy bồi theo kỹ thuật truyền thống. Ngày nay, mặt nạ còn được làm từ thạch cao, vàng lá và luôn được vẽ tay, thêm các chi tiết trang trí bằng lông chim, đá quí. Lavra là loại mặt nạ phổ biến và đặc trưng nhất của Venice, làm bằng sáp và thạch cao trắng như hình hồn ma, họa tiết đơn giản, nhưng có các chi tiết trang trí trên mũ cầu kỳ. Lễ hội hóa trang (Carnival) Venice được tổ chức vào khoảng trung tuần tháng 2 hàng năm, bắt đầu vào ngày thứ tư đầu tiên của Mùa Chay, kết thúc vào ngày Thứ ba sau đó 2 tuần. Đây là một dịp để mọi người vui chơi, hòa nhạc, khiêu vũ và cũng là dịp để ôn lại và ca ngợi lịch sử hình thành và cai trị một đất nước yên bình, phồn vinh, một xã hội công bằng, ổn định cũng như khích lệ tinh thần yêu nước của mỗi người dân .',
    url1:'imgs/lễ hội hóa trang (Ý)/lehoihoatrang-431.jpg',
    url2:'imgs/lễ hội hóa trang (Ý)/lehoihoatrang-432.jpg',
    url3:'imgs/lễ hội hóa trang (Ý)/lehoihoatrang-433.jpg',
    url4:'imgs/lễ hội hóa trang (Ý)/lehoihoatrang-hight1.jpg',
    url5:'imgs/lễ hội hóa trang (Ý)/lehoihoatrang-hight2.jpg',
    url6:'imgs/lễ hội hóa trang (Ý)/lehoihoatrang-hight3.jpg'
},
{
    nameLeHoi: 'Lễ hội hoa tulip',
    timeStart:'2018/03/22',
    timeEnd:'2018/05/20',
    diadiem: 'công viên Keukenhof, Hà Lan',
    kinhdo:'52.2700221',
    vido:'4.5442006',
    lucdia:'Châu Âu',
    tongiao:'Không',
    chitiet:'Mỗi độ xuân về, xứ sở “cối xay gió” lại náo nức đón chào lễ hội hoa tulip - một trong những sự kiện lớn nhất trong năm. Mỗi năm, lễ hội Keukenhof đưa ra một chủ đề đặc biệt và chủ đề năm nay là "Hà Lan" với triển lãm về lịch sử hình thành, cách gieo trồng hoa tulip. Bạn sẽ có cơ hội tìm hiểu các câu chuyện về hoa tulip mà người dân xứ này rất đỗi tự hào. Bên cạnh đó, lễ hội còn có các khu vườn hoa rực rỡ đầy sáng tạo được cắt tỉa khéo léo mô tả các biểu tượng đất nước Hà Lan để tạo nên một thành phố hoa thu nhỏ, tuyệt đẹp, cùng với hơn 60.000 bóng đèn hoa tulip được trang trí khắp các khu vườn. Lễ hội diễn ra từ ngày 22/03 – 20/05. Lễ hội chính được tổ chức tại công viên Keukenhof – vườn hoa lớn nhất thế giới thuộc thị trấn Lisse ở phía Tây Nam của thủ đô Amsterdam. Lễ hội mang tên: Lễ Hội Hoa KeukenhofNhững ngày lễ hội hoa Tulip Hà Lan diễn ra, dù nhiệt độ tại Hà Lan xuống thấp (chỉ khoảng 3 – 4 độ) nhưng những khóm hoa Tulip được trồng ở công viên Keukenhof vẫn đua nhau khoe sắc. Đây cũng là loài hoa được trộng nhiều nhất tại công viên trong số hơn 70 triệu bông hoa ôn đới với nhiều màu sắc sặc sỡ. Thời điểm thích hợp nhất cho bạn để thưởng ngoạn lễ hội hoa tulip chính là vào đầu tháng 4, khi các bông hoa bắt đầu nở rộ. Bạn cũng sẽ bắt gặp một không gian ấn tượng ở Keukenhof với những đài phun nước hình dáng độc đáo và những chiếc cối xay gió cổ kính nổi tiếng thế giới. Đây sẽ là điểm đến lý tưởng cho chuyến du lịch của bạn trong những ngày đầu tháng 4 sắp tới.',
    url1:'imgs/lễ hội hoa tulip (Hà Lan)/lehoihoatulip-431.jpg', 
    url2:'imgs/lễ hội hoa tulip (Hà Lan)/lehoihoatulip-432.jpg',
    url3:'imgs/lễ hội hoa tulip (Hà Lan)/lehoihoatulip-433.jpg',
    url4:'imgs/lễ hội hoa tulip (Hà Lan)/lehoihoatulip-hight1.jpg',
    url5:'imgs/lễ hội hoa tulip (Hà Lan)/lehoihoatulip-hight2.jpg',
    url6:'imgs/lễ hội hoa tulip (Hà Lan)/lehoihoatulip-hight3.jpg'
},
{
    nameLeHoi: 'Lễ hội Life Ball',
    timeStart:'2018/05/29',
    timeEnd:'2018/5/06',
    diadiem: 'Vienna, Áo',
    kinhdo:'48.220778',
    vido:'16.3100206',
    lucdia:'Châu Âu',
    tongiao:'Không',
    chitiet:'Lễ hội Life Ball được tổ chức bởi tổ chức phi lợi nhuận AIDS LIFE thành lập vào năm 1992 bởi Gery Keszler và Torgom Petrosian. Sự kiện đầu tiên diễn ra vào ngày 29 tháng 5 hàng năm tại Vienna( thủ đô của áo). Ngoài các chính quyền thành phố Vienna, sự kiện này chỉ có hai nhà tài trợ. Sự kiện được lập ra nhằm để hỗ trợ các tổ chức khác trong việc giúp đỡ những người có HIV dương tính hoặc có AIDS. Từ năm 1999, lễ hội được diễn ra tại cung điện Hofburg. Sự kiện từ thiện quyến rũ này được biết đến ra cả ngoài biên giới nước Áo. Đến nay, hơn 60 đài truyền hình và hơn 500 đại diện truyền thông quốc gia và quốc tế tham gia vào quan tâm sự kiện này mỗi năm.  Điều này cũng làm tăng nguồn vốn huy động của sự kiện Life Ball để có thể quyên góp cho các dự án và nghiên cứu bệnh AIDS nhiều hơn. Và trên hết, sự kiện có mục tiêu nhằm nâng cao nhận thức cộng đồng về các bệnh nhân liên quan tới AIDS và mục đích cao cả là kêu gọi mọi người ủng hộ quỹ dành cho người nhiễm HIV AIDS . ững bộ trang phục lộng lẫy sắc màu đặc biệt sẽ được nhiều người nổi tiếng khoác lên mình cùng với người dân nước Áo cùng bạn bè 5 châu với những điệu múa truyền thống. Ngoài ra, hàng năm đều có nhiều nhà thiết kế thời trang nổi tiếng chịu trách nhiệm cho các buổi biểu diễn thời trang của sự kiện Life Ball với sự tham gia những người mẫu chuyên nghiệp trên sàn catwalk như Marcus Schenkenberg, Alek Wek, Eva Padberg, Nadja Auermann, Heidi Klum, Eva Riccobono. Ngoài ra, sự kiện còn có sự xuất hiện bởi các ngôi sao và người nổi tiếng như Udo Kier, Olivia Jones, Til Schweiger, Kylie Minogue, Cyndi Lauper, Dolly Buster, Bộ trưởng y tế Áo Andrea Kdolsky. Tới với lễ hội Life Ball, bạn không chỉ được hòa mình trong những điệu múa truyền thống mà còn có cơ hội gặp gỡ những người có tên tuổi nổi tiếng thế giới, họ diện những bộ trang phục đẹp lộng lẫy và vô cùng cầu kỳ. Đặc biệt hơn, ngoài việc tham gia lễ hội, bạn còn có thể góp tiền hay quà tặng dành cho chương trình. Nếu bạn yêu thích sự kiện này, bạn hoàn toàn có thể trở thành tình nguyện viên của chương trình bằng việc đăng ký với tổ chức sự kiện Life Ball.',
    url1:'imgs/lifeball(Áo)/lifeball-431.jpg',
    url2:'imgs/lifeball(Áo)/lifeball-432.jpg',
    url3:'imgs/lifeball(Áo)/lifeball-433.jpg', 
    url4:'imgs/lifeball(Áo)/lifeball-hight1.jpg',
    url5:'imgs/lifeball(Áo)/lifeball-hight2.jpg',
    url6:'imgs/lifeball(Áo)/lifeball-hight3.jpg'
},
{
    nameLeHoi: 'Lễ hội ánh sáng',
    timeStart:'2018/06/23',
    timeEnd:'2018/06/30',
    diadiem: 'Nhà thờ lớn Berlin ,Đức',
    kinhdo:'52.5119642',
    vido:'13.3505705',
    lucdia:'Châu Âu',
    tongiao:'Không',
    chitiet:'Từ 10 đến 21/10, khoảng 50 công trình kiến trúc và danh thắng nổi tiếng ở khắp Berlin như quảng trường, đại lộ, các tháp tòa nhà hiện đại, được thay đổi diện mạo bằng ánh sáng rực rỡ màu sắc nhân dịp Lễ hội Ánh sáng Berlin thường niên. Các sự kiện bên lề cũng hứa hẹn độc đáo đầy hấp dẫn như: buổi hòa nhạc tại Nhà thờ Berlin, các chương trình Lightseeing cung cấp các tour du lịch mạo hiểm bằng xe buýt, thuyền và đi bộ. Suốt 12 năm qua, Lễ hội ánh sáng Berlin đã trở thành một thế giới đầy nghệ thuật của ánh sáng. Tại đây, các nghệ sĩ quốc tế thiết kế những tác phẩm nghệ thuật và truyền cảm hứng cho công chúng tham dự. Hơn 2 triệu lượt du khách, 650 nghìn đêm khách sạn, 1.8 tỷ địa chỉ liên lạc truyền thông, Lễ hội ánh sáng Berlin trở thành một trong những sự kiện cộng đồng thành công và là lễ hội ánh sáng lớn trên thế giới .',
    url1:'imgs/lễ hội ánh sáng (Đức)/lehoianhsang-431.jpg',
    url2:'imgs/lễ hội ánh sáng (Đức)/lehoianhsang-432.jpg', 
    url3:'imgs/lễ hội ánh sáng (Đức)/lehoianhsang-433.jpg', 
    url4:'imgs/lễ hội ánh sáng (Đức)/lehoianhsang-hight1.jpg',
    url5:'imgs/lễ hội ánh sáng (Đức)/lehoianhsang-hight2.jpg',
    url6:'imgs/lễ hội ánh sáng (Đức)/lehoianhsang-hight3.jpg'
},
{
    nameLeHoi: 'Lễ hội ném cà chua',
    timeStart:'2018/8/29',
    timeEnd:'2018/8/29',
    diadiem: 'Bunol, Tây Ban Nha',
    kinhdo:'39.4199219',
    vido:'-0.7932593',
    lucdia:'Châu Âu',
    tongiao:'Không',
    chitiet:'Lễ hội cà chua La Tomatina là lễ hội ném hoa quả lớn nhất châu Âu, được tổ chức vào ngày thứ Tư cuối cùng trong tháng 8 ở thị trấn Bunol, Valencia, Tây Ban Nha. Lễ hội thu hút hàng chục nghìn người từ khắp nơi trên thế giới đổ về đây để tham gia vào một “cuộc chiến” vô hại và vui vẻ, với hơn một tấn cà chua chín mọng được tung ném trên các đường phố.Trong một tuần diễn ra lễ hội có rất nhiều chương trình âm nhạc, diễu hành, nhảy múa, và bắn pháo hoa. Vào đêm trước ngày diễn ra hội ném cà chua, những người đến dự sẽ tham gia vào một cuộc thi nấu cơm đặc biệt: cơm thập cẩm paella. Vào khoảng 11h sáng, sự kiện đầu tiên của lễ hội Tomatina bắt đầu. Người ta treo một miếng thịt đùi nướng lên trên chiếc cột cao đã được bôi mỡ trơn. Trận chiến cà chua chỉ được bắt đầu khi có người leo lên tới đỉnh cột và mang miếng thịt xuống. Mọi người bắt đầu tranh đua lẫn nhau, người nọ leo sau người kia, tất cả đều cố gắng giành chiến thắng để lễ hội khai cuộc.Trận chiến ném cà chua trên đường phố bắt đầu bằng một tiếng nổ rền vang của khẩu thần công trong thị trấn. Mọi người được khuyến khích mang kính che mắt và đeo găng tay. Ngoài ra, để đảm bảo an toàn, những người tham gia phải bóp nát quả cà chua trước khi ném vào người khácTrận chiến ồn ào, hỗn loạn với cà chua này sẽ kéo dài trong khoảng 1 đến 2 giờ. Người ta ném cà chua vào nhau, và vào những chiếc xe tải đang ùn ùn đổ về mang theo những đống cà chua lớn. Khi một tiếng nổ rền vang lại phát ra từ khẩu thần công chính là lúc cuộc chơi kết thúc. Không ai còn được phép ném cà chua trên phố nữa.Công cuộc dọn dẹp vệ sinh thị trấn ngay lập tức bắt đầu với những chiếc xe chữa cháy tiến vào phun nước lên tất cả các con đường. Mọi người thì đổ về con sông Bunol tắm gội.Lễ hội cà chua được tổ chức trùng với ngày thánh Luis Bertran - vị thần hộ mệnh của thành phố, và Đức mẹ đồng trinh Mare de Déu dels Desemparats. Không ai biết nguồn gốc và mục đích thực sự của lễ hội là gì. Có giả thuyết cho rằng truyền thống này bắt đầu từ tục lệ ném cà chua vào đoàn người diễu hành trong các lễ hội để trêu chọc, phản đối những ca sĩ tồi. Một giả thuyết khác có vẻ thuyết phục hơn là lễ hội này bắt đầu từ khi người dân trong thị trấn bất bình trước cách thức điều hành của chính quyền nơi đây và bắt đầu ném cà chua vào các quan chức để phản đối. Dần dần, hình thức này được phát triển thành lễ hội, và thực sự nổi tiếng sau khi được phát sóng trên truyền hình Tây Ban Nha .',
    url1:'imgs/lễ hôi ném cà chua (Tây Ban Nha)/lehoicachua-431.jpg',
    url2:'imgs/lễ hôi ném cà chua (Tây Ban Nha)/lehoicachua-432.jpg',
    url3:'imgs/lễ hôi ném cà chua (Tây Ban Nha)/lehoicachua-433.jpg',
    url4:'imgs/lễ hôi ném cà chua (Tây Ban Nha)/lehoicachua-hight1.jpg',
    url5:'imgs/lễ hôi ném cà chua (Tây Ban Nha)/lehoicachua-hight2.jpg',
    url6:'imgs/lễ hôi ném cà chua (Tây Ban Nha)/lehoicachua-hight3.jpg'
},
{
    nameLeHoi: 'Lễ hội Agitagueda',
    timeStart:'2018/07/23',
    timeEnd:'2018/07/31',
    diadiem: 'Agitagueda, Bồ Đào Nha',
    kinhdo:'40.5721869',
    vido:'-8.4491686',
    lucdia:'Châu Âu',
    tongiao:'Không',
    chitiet:'Trong những ngày cuối tháng 7/2013, trên đường phố Agueda, Bồ Đào Nha đang tràn ngập sắc màu rực rỡ bởi những chiếc ô được treo lơ lửng. Đây chính là một phần đặc sắc của lễ hội nghệ thuật Agitagueda. Được biết, Ý tưởng độc đáo này là của một nhà thiết kế người Bồ Đào Nha – Ivotavares. Nhà thiết kế Ivotavares lựa chọn phố Agueda làm địa điểm trình bày ý tưởng của mình với mục đích biến một con phố mua sắm truyền thống trở nên hấp dẫn hơn và mang đến những trải nghiệm mới lạ cho khách tham quan và bạn bè quốc tế. Những chiếc “ô bay” này tồn tại trong suốt thời gian diễn ra lễ hội nghệ thuật Agitagueda. Với nhiều hoạ tiết, hình vẽ đẹp, lạ mắt cùng nhiều màu sắc sinh động, con "phố ô" Agueda đã thu hút sự quan tâm của đông đảo người dân và khách du lịch. Nếu đang du lịch tại Bồ Đào Nha hoặc sang đây vào những ngày này, bạn hãy tận hưởng dịp hiếm có để tham gia vào các hoạt động của lễ hội nghệ thuật Agitagueda. Đặc biệt, bạn không nên bỏ lỡ cơ hội được tản bộ dưới bóng mát của "phố ô” rực rỡ này và lưu lại những bức hình đáng nhớ cho chuyến du lịch của mình .',
    url1:'imgs/lễ hội ô (Bồ Đào Nha)/lehoio-431.jpg',
    url2:'imgs/lễ hội ô (Bồ Đào Nha)/lehoio-432.jpg',
    url3:'imgs/lễ hội ô (Bồ Đào Nha)/lehoio-433.jpg',
    url4:'imgs/lễ hội ô (Bồ Đào Nha)/lehoio-hight1.jpg',
    url5:'imgs/lễ hội ô (Bồ Đào Nha)/lehoio-hight2.jpg',
    url6:'imgs/lễ hội ô (Bồ Đào Nha)/lehoio-hight3.jpg'
},
{
    nameLeHoi: 'Lễ hội thánh Patrick',
    timeStart:'2018/03/17',
    timeEnd:'2018/03/17',
    diadiem: 'Ireland',
    kinhdo:'53.3975179',
    vido:'-10.1980727',
    lucdia:'Châu Âu',
    tongiao:'Đạo Thiên Chúa',
    chitiet:'Lễ Thánh Patrick là lễ hội quốc gia ở Ireland. Vào ngày này, tất cả mọi người dừng hết tất cả công việc và cùng nhau hưởng trọn không khí tưng bừng của lễ hội. Các bệnh viện, ngân hàng, trường học... tất cả đều đóng của để cháo đón lễ hội. Ngày lễ thánh Patrick được chính thức công khai là ngày lễ quốc gia vào khoảng thế kỷ 17, và dần dần trở thành ngày lễ tượng trưng cho nền văn hóa của người Ireland. Có rất nhiều truyền thuyết liên quan đến Thánh Patrick. Một trong số đó là Patrick có khả năng làm người chết sống dậy. Và huyền thoại lớn nhất về Thánh Patrick là khi ông giảng đạo trên đỉnh một ngọn đồi và đặt lời nguyền của Thiên chúa giáo, khiến cho toàn bộ các loài rắn có nọc độc bị đuổi khỏi Ireland và chết ngoài biển khơi. Có thể nói, rắn là hình ảnh ẩn dụ cho những tà giáo đã được Thánh Patrick loại bỏ khỏi Ireland. Người ta nói rằng ông đã sử dụng cỏ 3 lá shamrock mọc trên đất Ireland để giải thích cho dân chúng về học thuyết “Ba ngôi một thể” (The Trinity) trong Thiên chúa giáo vào thế kỷ thứ 5. Ông sử dụng hình ảnh này trong các bài giảng đạo của mình để diễn tả tại sao Cha, Con và Thánh Thần lại có thể tồn tại như những thành phần riêng biệt, ngang nhau về đặc tính và quyền năng của một thực thể giống nhau. Đến nay, vào ngày thánh Patrick hàng năm, cộng đồng người Ireland vẫn thường mặc trang phục màu xanh lá có hình cây cỏ 3 lá để kỷ niệm truyền thuyết này. Cỏ 3 lá này cũng trở thành biểu tượng cho niềm tin, hy vọng và sự đâm trồi nảy lộc của đất nước Ireland. Cỏ 3 lá là một chi thuộc họ Đậu, có thân mềm, sống một năm hoặc lâu năm, có 3 lá (rất hiếm cây có 5 hay 7 lá) đặc biệt những cây cỏ 4 lá được xem là biểu tượng của sự may mắn. Từ truyền thuyết này mà vào ngày lễ hội, toàn bộ mọi thứ trên khắp các con đường và góc phố dường như được  nhuộm thành màu xanh. Từ con người đến đồ vật, thức ăn... tất thảy đều khoác lên mình bộ cánh màu xanh. Có người còn trang trí cỏ ba lá lên mặt, lên quần áo và các vật dụng, có người thì chọn cho mình một chiếc mũ yêu tinh đầy tinh nghịch, hay ở một vài nơi, người dân còn nhuôm xanh cảm một  dòng sông, đài tưởng niệm và thậm chí cả khu trượt tuyết cũng biến thành màu xanh để kỷ niệm dịp này. Đối với người Ireland, màu xanh còn thể hiện tình yêu dân tộc hay niềm tin tôn giáo, từ những cụ bà đeo khăn choàng xanh, cài huy hiệu xanh đến các cô gái đeo bờm xanh đến cả nhưng cô bé cậu bé nhỏ mặc những bộ cánh dễ thương cũng trong một màu xanh ngắt .',
    url1:'imgs/lễ hội thánh Patrick (Ireland)/patrick-431.jpg',
    url2:'imgs/lễ hội thánh Patrick (Ireland)/patrick-432.jpg',
    url3:'imgs/lễ hội thánh Patrick (Ireland)/patrick-433.jpg',
    url4:'imgs/lễ hội thánh Patrick (Ireland)/patrick-hight1.JPG',
    url5:'imgs/lễ hội thánh Patrick (Ireland)/patrick-hight2.jpg',
    url6:'imgs/lễ hội thánh Patrick (Ireland)/patrick-hight3.jpg'
}
];