var  festival = [{
    nameLeHoi: 'Lễ Hội Mặt Nạ',
    tiemStart:'2018/01/24',
    timeEnd:'2018/01/25',
    diadiem: 'Bờ Biển Ngà',
    kinhdo:'7.4608409',
    vido:'-7.7926176,7',
    lucdia:'Châu Phi',
    tongiao:'Không',
    chitiet:'Bất cứ ai quan tâm đến nền văn hóa châu Phi thì đều không thể nào bỏ qua lễ hội này. Đây là lễ hội được tổ chức nhằm mục đích bày tỏ lòng kính trọng cho các linh hồn của rừng. Các vũ công sẽ đeo mặt nạ và mặc những bộ trang phục nhiều màu sắc tham gia thi khiêu vũ để dân làng chọn lựa ra vũ công xuất sắc.',
    url1:'imgs/Lễ Hội Mặt Nạ/Fetes-des-Masques1-5c399.jpg',
    url2:'imgs/Lễ Hội Mặt Nạ/human-planet-timothy-allen-04.jpg', 
    url3:'imgs/Lễ Hội Mặt Nạ/Mombasa-Carnival1-5c399.jpg', 
    url4:'imgs/Lễ Hội Mặt Nạ/img2432.jpg',
    url5:'imgs/Lễ Hội Mặt Nạ/le-hoi-bo-bien-nga-6.jpg',
    url6:'imgs/Lễ Hội Mặt Nạ/maxresdefault.jpg'
},
{
    nameLeHoi: 'Lễ Hội Mombasa',
    tiemStart:'2018/10/30',
    timeEnd:'2018/10/31',
    diadiem: 'Kenya',
    kinhdo:'0.1540839',
    vido:'33.4078752,6',
    lucdia:'Châu Phi',
    tongiao:'Không',
    chitiet:'Nếu bạn có cơ hội đến Kenya, hãy tham gia vào lễ hội Mombasa Carnival sôi động và nhiều màu sắc. Mọi người sẽ tham dự các cuộc diễu hành trên khắp đường phố trong những trang mục đẹp mắt, sặc sỡ sắc màu với âm nhạc sôi động.',
    url1:'imgs/Lễ Hội Mombasa/02nxg_p3_mambosa_g611qvoil102nxg_mombasa_carnival1jpg3.jpg',
    url2:'imgs/Lễ Hội Mombasa/856803-white-faced-warrior-from-africa-band.jpeg', 
    url3:'imgs/Lễ Hội Mombasa/mombasa-carnival7.jpg', 
    url4:'imgs/Lễ Hội Mombasa/cultural-festival-mombasa.jpg',
    url5:'imgs/Lễ Hội Mombasa/festival-1.jpg',
    url6:'imgs/Lễ Hội Mombasa/Kenya-maasai.jpg'
},
{
    nameLeHoi: 'Lễ Panafest',
    tiemStart:'2018/05/10',
    timeEnd:'2018/05/11',
    diadiem: 'Ghana',
    kinhdo:'7.8984748',
    vido:'-3.2754727,7',
    lucdia:'Châu Phi',
    tongiao:'Không',
    chitiet:'Đối với người dân đến từ lục địa đen, Panafest là một từ đã quá quen thuộc, diễn ra vào tháng 7, tháng 8 và thường được tổ chức hai năm một lần tại đất nước Ghana. Lễ hội được tổ chức lần đầu vào năm 1992, với ý tưởng quảng bá và thắt chặt tình đoàn kết giữa những đất nước châu Phi, với vô số hoạt động thú vị và đầy màu sắc như: kịch, thơ, múa, biểu diễn âm nhạc, trống và đặc biệt nhất là lễ rước tộc trưởng và vợ. Họ được rước lên đài, trong tiếng hò reo của người dân Ghana và tiếng trống đậm chất châu Phi.',
    url1:'imgs/Lễ Hội Panafest/34826f0547cb4a8a867e02a97fd71975.jpg', 
    url2:'imgs/Lễ Hội Panafest/Panafest-874x492.jpg',
    url3:'imgs/Lễ Hội Panafest/panfest.jpg',
    url4:'imgs/Lễ Hội Panafest/B9317088446Z.1_20150425185319_000_G8OAJU67F.1-0.jpg',
    url5:'imgs/Lễ Hội Panafest/DSC01083.jpg',
    url6:'imgs/Lễ Hội Panafest/Princess_Swaziland_014.jpg'
},
];