var  festival = [{
    nameLeHoi: 'Lễ mừng Đức Phật đản sinh',
    tiemStart:'2018/01/24',
    timeEnd:'2018/01/25',
    diadiem: 'Việt Nam',
    kinhdo:'15.7587298',
    vido:'101.4157145',
    lucdia:'Châu Á',
    tongiao:'Đạo Phật',
    chitiet:'Phật Đản (chữ Nho 佛誕 -nghĩa là ngày sinh của đức Phật); hay là Vesak (Pali; tiếng Phạn: Vaiśākha, Devanagari: वैशाख, Sinhala: වෙසක් පෝය) là ngày kỷ niệm Phật Tất-đạt-đa Cồ-đàm sinh ra tại vườn Lâm-tì-ni, năm 624 TCN, diễn ra vào ngày 15 tháng 4 âm lịch hàng năm. Theo truyền thống Phật giáo Bắc tông và ảnh hưởng của Phật giáo Trung Hoa, ngày này chỉ là ngày kỷ niệm ngày sinh của đức Phật Thích Ca; tuy nhiên, theo Phật giáo Nam truyền và Phật giáo Tây Tạng thì ngày này là ngày Tam hiệp (kỷ niệm Phật đản, Phật thành đạo và Phật nhập Niết-bàn). Ngày Phật Đản hay là lễ Vesak, Tam Hiệp được kỷ niệm vào các ngày khác nhau, tùy theo quốc gia. Một số quốc gia với đa số Phật tử chịu ảnh hưởng Bắc tông (như Trung Quốc, Hàn Quốc, Nhật Bản, Việt Nam) thường tổ chức ngày lễ Phật đản vào ngày mồng 8 tháng 4 âm lịch. Các quốc gia theo Nam tông thường tổ chức vào ngày trăng tròn trong tháng 4 âm lịch hay là ngày trăng tròn trong tháng 5 dương lịch. Có những năm có 2 ngày trăng tròn trong tháng 5 dương lịch như năm 2007, có nơi tổ chức ngày Vesak vào ngày trăng tròn đầu tiên (ngày 1 tháng 5) trong khi tại nơi khác lại kỷ niệm vào ngày trăng tròn thứ 2 (ngày 31 tháng 5).[1] Cách tính kỷ nguyên Phật lịch tại các quốc gia theo truyền thống Nam tông cũng khác nhau, nên năm Phật lịch có thể cách nhau một năm.',
    price:'150000',
    url1:'imgs/Đức Phật Đản Sinh/Phậtđản-431.jpg',
    url2:'imgs/Đức Phật Đản Sinh/Phậtđản-432.JPG', 
    url3:'imgs/Đức Phật Đản Sinh/Phậtđản-433.jpg', 
    url4:'imgs/Đức Phật Đản Sinh/Phậtđản-hight1.jpg',
    url5:'imgs/Đức Phật Đản Sinh/Phậtđản-hight2.jpg',
    url6:'imgs/Đức Phật Đản Sinh/Phậtđản-hight3.jpg'
},
{
    nameLeHoi: 'Lễ khánh đản Đức Phật Dược Sư',
    tiemStart:'2018/10/30',
    timeEnd:'2018/10/31',
    diadiem: 'Trung Quốc',
    kinhdo:'34.4561427',
    vido:'86.0826666',
    lucdia:'Châu Á',
    tongiao:'Đạo Phật',
    chitiet:'Phật Dược Sư (tiếng Phạn: bhaiṣajyaguru; chữ Hán: 藥師佛; nghĩa là "vị Phật thầy thuốc"), còn gọi là Dược Sư Lưu Ly Quang Vương Phật (bhaiṣajyaguruvaidūrya-prabha-buddha; 藥師琉璃光佛), Dược Sư Lưu Ly Quang Vương Như Lai (Phạn: Bhaiṣaijya guru vaiḍuria prabhà ràjàya tathàgatàya), Dược Sư Như Lai (Phạn: Bhaiṣaijya guru tathàgatàya), Dược Sư Lưu Ly Như Lai (Phạn: Bhaiṣaijya guru vaiḍuria tathàgatàya), Đại Y Vương Phật (Phạn: Mahà Bhaiṣaijya ràja buddha), Vương Thiện Đạo, do bổn nguyện của ngài là "cứu tất cả các bệnh khổ cho các chúng sinh" cho nên còn có tên Tiêu Tai Diên Thọ Dược Sư Phật[1], là vị Phật đại diện cho sự trọn vẹn của Phật quả ngự cõi phía đông (là cõi Tịnh Lưu ly). Tranh tượng của vị Phật này hay được vẽ với tay trái cầm thuốc chữa bệnh và tay mặt giữ Ấn thí nguyện. Phật Dược Sư thường được thờ chung với Phật Thích Ca Mâu Ni và A Di Đà, trong đó phật Dược Sư đứng bên trái còn Phật A Di Đà đứng bên phải Phật Thích Ca. Trong kinh Dược Sư, hiện nay chỉ còn bản chữ Hán và chữ Tây Tạng, người ta đọc thấy 12 lời nguyện của vị Phật này, thệ cứu độ chúng sinh, với sự giúp đỡ của chư Phật, Bồ Tát và 12 vị Hộ pháp và Thiên vương. Tại Trung Quốc, Tây Tạng, Nhật Bản và Việt Nam, Phật Dược Sư được thờ cúng rộng rãi.',
    price:'150000',
    url1:'imgs/Đức Phật Dược Sư/Đức Phât Dược Sư-431.jpg',
    url2:'imgs/Đức Phật Dược Sư/Đức Phật Dược Sư-432.jpg', 
    url3:'imgs/Đức Phật Dược Sư/Đức Phật Dược Sư-433.jpg', 
    url4:'imgs/Đức Phật Dược Sư/Đức Phật Dược Sư-hight1.jpg',
    url5:'imgs/Đức Phật Dược Sư/Đức Phật Dược Sư-hight2.jpg',
    url6:'imgs/Đức Phật Dược Sư/Đức Phật Dược Sư-hight3.jpg'
},
{
    nameLeHoi: 'Lễ khánh đản Đức Văn Thù Bồ Tát',
    tiemStart:'2018/05/10',
    timeEnd:'2018/05/11',
    diadiem: 'Trung Quốc',
    kinhdo:'34.4561427',
    vido:'86.0826666',
    lucdia:'Châu Á',
    tongiao:'Đạo Phật',
    chitiet:'Văn-thù-sư-lợi (zh. 文殊師利, sa. mañjuśrī) là tên dịch theo âm, thường được gọi tắt là Văn-thù, dịch nghĩa là Diệu Đức (zh. 妙德), Diệu Cát Tường (zh. 妙吉祥), cũng có lúc được gọi là Diệu Âm (zh. 妙音), dịch từ tên tiếng Phạn là Mañjughoṣa, là một vị Bồ Tát tượng trưng cho trí huệ, một trong những vị Bồ Tát quan trọng của Phật giáo. Lần đầu tiên người ta nhắc đến Văn-thù trong tác phẩm Văn-thù-sư-lợi căn bản nghi quỹ (sa. ārya-mañjuśrī-mūlakalpa) ở thế kỉ thứ 4. Tranh tượng trình bày Văn-thù với lưỡi kiếm và kinh Bát-nhã-ba-la-mật-đa, được vẽ khoảng ngang đầu. Người ta xem đó là biểu tượng trí huệ phá đêm tối của Vô minh. Về sau chúng ta thường thấy Văn-thù cưỡi trên một con sư tử. Trong Phật giáo Tây Tạng, các vị luận sư xuất sắc như Tông-khách-ba thường được xem là hiện thân của Văn-thù (Châu-cô). Dưới tên Diệu Âm (zh. 妙音), "Người với tiếng nói êm dịu", Văn-thù Bồ Tát thường được tán tụng trước khi hành giả nghiên cứu kinh điển, nhất là kinh điển thuộc hệ Bát-nhã-ba-la-mật-đa và học thuyết của Trung quán tông. Văn-thù là vị Bồ Tát tượng trưng cho kinh nghiệm giác ngộ, đạt được bằng phương tiện tri thức. Văn-thù cũng xuất hiện dưới dạng một Thần thể (sa. iṣṭadevatā, sādhita, bo. yidam) phẫn nộ, có tên gọi là Diêm-mạn-đức-ca – "Người chiến thắng tử thần" (sa. yamāntaka), có dạng vị thần mang đầu bò. Dạng này là Thần thể quan trọng của phái Cách-lỗ tại Tây Tạng. Theo truyền thống Phật giáo Trung Quốc, Văn-thù được Phật Thích-ca đích thân giao phó việc truyền bá Phật pháp tại đây và Ngũ Đài sơn chính là nơi Bồ Tát thuyết pháp. Vì vậy, Ngũ Đài sơn cũng được xem là trụ xứ của Văn-thù (xem Tứ đại danh sơn). Một thuyết khác bảo rằng, Bồ Tát đã từng xuất hiện tại Trung Quốc trong thế kỉ 1, đời Hán Minh Đế. Câu niệm danh hiệu của vị bồ tát này là: "Nam mô đại trí văn thù sư lợi bồ tát".',
    price:'150000',
    url1:'imgs/Văn Thù Bồ Tát/Văn Thù Bồ Tát-431.jpg', 
    url2:'imgs/Văn Thù Bồ Tát/Văn Thù Bồ Tát-432.jpg',
    url3:'imgs/Văn Thù Bồ Tát/Văn Thù Bồ Tát-433.jpg',
    url4:'imgs/Văn Thù Bồ Tát/Văn Thù Bồ Tát-hight1.jpg',
    url5:'imgs/Văn Thù Bồ Tát/Văn Thù Bồ Tát-hight2.jpg',
    url6:'imgs/Văn Thù Bồ Tát/Văn Thù Bồ Tát-hight3.jpg'
},
{
    nameLeHoi: 'Lễ khánh đản Đức Phổ Hiền Bồ Tát',
    tiemStart:'2018/03/28',
    timeEnd:'2018/03/29',
    diadiem: 'Trung Quốc',
    kinhdo:'34.4561427',
    vido:'86.0826666',
    lucdia:'Châu Á',
    tongiao:'Đạo Phật',
    chitiet:'Phổ Hiền Bồ tát (dịch âm là Tam mạn đà bạt đà la, hoặc Tam mạn đà bạt đà, zh. pǔxián 普賢, sa. samantabhadra, ja. fugen, bo. kun tu bzang po ཀུན་ཏུ་བཟང་པོ་). Phổ là biến khắp, Hiền là Đẳng giác Bồ tát, Phổ Hiền là vị Bồ tát Đẳng giác có năng lực hiện thân khắp mười phương pháp giới, tùy mong cầu của chúng sanh mà hiện thân hóa độ. Ngài là một trong những vị Bồ Tát quan trọng trong Phật giáo Đại thừa. Theo kinh Pháp Hoa, Ngài là vị Bồ tát ở quốc độ của Phật Bảo Oai Đức Thượng Vương Như Lai, phía Đông cõi Ta Bà, nghe thế giới này thuyết kinh Pháp Hoa liền lãnh đạo năm trăm vị Đại Bồ tát đến nghe pháp và phát tâm hộ trì Chánh pháp của Đức Phật Thích Ca. Phổ Hiền được xem là người hộ vệ của những ai tuyên giảng đạo pháp và đại diện cho "Bình đẳng tính trí" tức là trí huệ thấu hiểu cái nhất thể của sự đồng nhất và khác biệt. Bồ Tát Phổ Hiền hay được thờ chung với Phật Thích-ca và Bồ Tát Văn-thù-sư-lợi (sa. mañjuśrī). Bồ Tát cưỡi voi trắng sáu ngà, voi trắng tượng trưng cho trí huệ vượt chướng ngại, sáu ngà cho sự chiến thắng sáu giác quan. Trong hệ thống Ngũ Phật, Phổ Hiền được xem ở trong nhóm của Phật Đại Nhật (sa. vairocana). Biểu tượng của Phổ Hiền là ngọc như ý, hoa sen, có khi là trang sách ghi thần chú của Bồ Tát. Tại Trung Quốc, Phổ Hiền được xem là một trong bốn Đại Bồ Tát, trú xứ của Phổ Hiền là núi Nga Mi, nơi Bồ Tát lưu trú sau khi cưỡi voi trắng sáu răng (sáu răng ngụ ý sáu độ, sáu phương pháp tu hành để đạt tới cõi Niết bàn; bốn chân biểu thị bốn điều như ý, bốn loại thiền định) từ Ấn Độ sang Trung Quốc.',
    price:'150000',
    url1:'imgs/Phổ Hiền Bồ Tát/Phổ Hiền Bồ Tát-431.jpg',
    url2:'imgs/Phổ Hiền Bồ Tát/Phổ Hiền Bồ Tát-432.jpg',
    url3:'imgs/Phổ Hiền Bồ Tát/Phổ Hiền Bồ Tát-433.png',
    url4:'imgs/Phổ Hiền Bồ Tát/Phổ Hiền Bồ Tát-hight1.jpg',
    url5:'imgs/Phổ Hiền Bồ Tát/Phổ Hiền Bồ Tát-hight2.jpg',
    url6:'imgs/Phổ Hiền Bồ Tát/Phổ Hiền Bồ Tát-hight3.jpg'
},
{
    nameLeHoi: 'Lễ khánh đản Đức Chuẩn Đề Bồ Tát',
    tiemStart:'2018/05/01',
    timeEnd:'2018/05/02',
    diadiem: 'Trung Quốc',
    kinhdo:'34.4561427',
    vido:'86.0826666',
    lucdia:'Châu Á',
    tongiao:'Đạo Phật',
    chitiet:'Phật Mẫu Chuẩn Đề tên Phạn là Cundì, Cunïdïhi(चुन्दी), tên chữ Hán là Thất Câu Chi Phật Mẫu hay Thất Câu Đê Phật Mẫu, Chuẩn Đề Bồ Tát. Ngài là một trong lục quan âm của Phật giáo, trong Tạng Giới Man Đa La ghi Chuẩn Đề là một trong 3 vị Phật Mẫu thuộc Biến Tri Viện. Chuẩn Đề là một vị bồ tát trong trường phái Đại thừa, và đặc biệt được nhắc đến nhiều trong Kim cương thừa. Bà được xem là Bhagavathi (trong tiếng Phạn có nghĩa là "nữ thần"), hay "mẹ của các Phật", và thường được xem là ngang hàng với Quán Thế Âm. Chuẩn Đề có thể có liên quan đến vị nữ thần Chandi trong Ấn Độ giáo. Thân vị Bồ-tát nầy có màu vàng trắng hay màu vàng lợt, ngồi kiết gia trên đài sen, có hào quang tỏa sáng xung quanh, mình mặc thiên y, trên đầu trang điểm ngọc anh lạc. Đầu đội mão báu có ngọc lưu ly rũ treo, có 18 tay đều đeo vòng xuyến khảm Xà Cừ và mỗi tay đều cầm các loại khí cụ biểu thị cho các Tam Muội Gia, gồm có 3 mắt. Vị Bồ-tát nầy chuyên hộ trì Phật pháp và bảo hộ những chúng sinh có mạng sống ngắn ngủi được thọ mạng lâu dài. Pháp môn tu hành của vị Bồ-tát nầy là trì tụng bài chú: Nam mô tát đa nẫm, tam miệu tam bồ đà Câu chi nẫm, đát diệt tha: án, chiết lệ chủ lệ chuẩn đề ta bà ha.',
    price:'150000',
    url1:'imgs/Chuẩn Đề Bồ Tát/Phật Bà Nghìn Mắt Nghìn Tay-431.jpg',
    url2:'imgs/Chuẩn Đề Bồ Tát/Phật Bà Nghìn Mắt Nghìn Tay-432.jpg',
    url3:'imgs/Chuẩn Đề Bồ Tát/Phật Bà Nghìn Mắt Nghìn Tay-433.jpg', 
    url4:'imgs/Chuẩn Đề Bồ Tát/Phật Bà Nghìn Mắt Nghìn Tay-hight1.jpg',
    url5:'imgs/Chuẩn Đề Bồ Tát/Phật Bà Nghìn Mắt Nghìn Tay-hight2.jpg',
    url6:'imgs/Chuẩn Đề Bồ Tát/Phật Bà Nghìn Mắt Nghìn Tay-hight3.jpg'
},
{
    nameLeHoi: 'Lễ khánh đản Địa Tạng Bồ Tát',
    tiemStart:'2018/09/09',
    timeEnd:'2018/09/10',
    diadiem: 'Trung quốc',
    kinhdo:'34.4561427',
    vido:'86.0826666',
    lucdia:'Châu Á',
    tongiao:'Đạo Phật',
    chitiet:'Địa Tạng, Địa Tạng Vương (skt. क्षितिगर्भ, Kṣitigarbha; tiếng Trung: 地藏; bính âm: Dìzàng; Wade–Giles: Ti-tsang; jap. 地蔵, Jizō; tib. ས་ཡི་སྙིང་པོ.sai snying po, kor.: 지장, 지장보살, ji jang, ji jang bosal[1]) là một vị Bồ-tát được tôn thờ trong Phật giáo Đông Á, thường được mô tả như một tỉ-khâu phương Đông. Địa Tạng Bồ-tát được biết đến bởi lời nguyện cứu độ tất cả chúng sinh trong lục đạo luân hồi vào thời kỳ sau khi Phật Thích-ca Mâu-ni nhập Niết-bàn cho đến khi Bồ-tát Di Lặc hạ sanh, và nguyện không chứng Phật quả nếu địa ngục chưa trống rỗng. Do đó, Địa Tạng thường được xem như là vị Bồ-tát của chúng sanh dưới địa ngục hay là giáo chủ của cõi U Minh.[2] Trong văn hóa Nhật Bản, Địa Tạng là Bồ-tát hộ mệnh cho trẻ em, cũng như bảo vệ các vong linh của trẻ em hoặc bào thai chết yểu. Địa Tạng thường được mô tả là một tỉ-khâu trọc đầu với vầng hào quang, một tay cầm tích trượng để mở cửa địa ngục, tay kia cầm ngọc Như Ý tượng trưng cho ánh sáng xua tan bóng đêm. Một số tranh tượng ở Trung Quốc và Việt Nam cũng khắc họa Địa Tạng Vương Bồ tát đội mũ thất phật và mặc cà sa đỏ - hình ảnh tu sĩ Phật giáo Bắc Truyền, hình tượng nhân vật Đường Tăng trong tiểu thuyết Tây Du Ký rất giống hình tượng của Đức Bồ Tát. Địa Tạng Vương Bồ tát là một trong 6 vị bồ tát quan trọng của Phật giáo Đại thừa. 5 vị còn lại là các Quán Thế Âm Bồ tát, Đại Thế Chí Bồ tát, Văn Thù Sư Lợi Bồ tát, Phổ Hiền Bồ tát và Di Lặc Bồ tát.',
    price:'150000',
    url1:'imgs/Địa Tạng Bồ Tát/Địa Tạng Bồ Tát-431.jpg',
    url2:'imgs/Địa Tạng Bồ Tát/Địa Tạng Bồ Tát-432.jpg',
    url3:'imgs/Địa Tạng Bồ Tát/Địa Tạng Bồ Tát-433.jpg',
    url4:'imgs/Địa Tạng Bồ Tát/Địa Tạng Bồ Tát-hight1.jpg',
    url5:'imgs/Địa Tạng Bồ Tát/Địa Tạng Bồ Tát-hight2.jpg',
    url6:'imgs/Địa Tạng Bồ Tát/Địa Tạng Bồ Tát-hight3.jpg'
},
{
    nameLeHoi: 'Lễ khánh đản Đại Thế Chí Bồ Tát',
    tiemStart:'2018/08/23',
    timeEnd:'2018/08/24',
    diadiem: 'Trung Quốc',
    kinhdo:'34.4561427',
    vido:'86.0826666',
    lucdia:'Châu Á',
    tongiao:'Đạo Phật',
    chitiet:'Đại Thế Chí Bồ Tát còn được gọi là Đắc Đại Thế Bồ tát, Đại Tinh Tấn Bồ tát, Vô Biên Quang Bồ tát,Linh Cát Bồ tát,… hay vắn tắt là Thế Chí. Ngài là vị Bồ tát thường dùng ánh sáng trí tuệ chiếu khắp mọi loài, khiến chúng sanh mười phương thế giới thoát khổ đau, thành tựu đạo quả Bồ đề. Đắc Đại Thế Bồ tát vì Bồ tát có hạnh nguyện đại hùng đại lực đại từ bi, dùng hạnh nguyện này để trụ trong Ta bà thế giới, điều phục và tiếp độ chúng sanh cang cường. Trong Kinh Đại Bi Liên Hoa (Kinh Bi Hoa), tiền thân của Đại Thế Chí Bồ Tát là Ni-ma vương tử, người con thứ hai của Chuyển luân vương Vô Chánh Niệm (sau này là Đức Phật A Di Đà). Bồ tát được Phật Bảo Tạng thọ ký rằng, trong đời vị lai vô lượng vô biên kiếp, sau khi Đức Phật Biến Xuất Nhất Thiết Công Đức Sơn Vương Như Lai nhập niết bàn (tức Quán Thế Âm Bồ Tát thành Phật trong đời vị lai), Đại Thế Chí Bồ tát sẽ thay ngài tiếp quản chánh pháp và thế giới phương tây, thành Phật hiệu là Thiện Trụ Trân Bảo Sơn Vương Như Lai, Ứng cúng, Chánh biến tri, Minh hạnh túc, Thiện thệ, Thế gian giải, Vô thượng sĩ, Điều ngự trượng phu, Thiên nhân sư, Phật, Thế Tôn.',
    price:'150000',
    url1:'imgs/Đại Thế Chí Bồ Tát/Đại Thế Chí Bồ Tát-431.jpg', 
    url2:'imgs/Đại Thế Chí Bồ Tát/Đại Thế Chí Bồ Tát-432.jpg',
    url3:'imgs/Đại Thế Chí Bồ Tát/Đại Thế Chí Bồ Tát-433.JPG',
    url4:'imgs/Đại Thế Chí Bồ Tát/Đại Thế Chí Bồ Tát-hight1.jpg',
    url5:'imgs/Đại Thế Chí Bồ Tát/Đại Thế Chí Bồ Tát-hight2.jpg',
    url6:'imgs/Đại Thế Chí Bồ Tát/Đại Thế Chí Bồ Tát-hight3.jpg'
},
{
    nameLeHoi: 'Lễ Thượng Nguyên',
    tiemStart:'2018/06/18',
    timeEnd:'2018/03/02',
    diadiem: 'Việt Nam',
    kinhdo:'15.7587298',
    vido:'101.4157145',
    lucdia:'Châu Á',
    tongiao:'Đạo Phật',
    chitiet:'Rằm tháng Giêng hay Tết Nguyên Tiêu trong truyền thống Phật giáo Nam tông là lễ hội Cúng Dường Đức Phật đầu năm, mong cầu phát sinh sự an lành, hạnh phúc, theo dân gian là lễ hội kết thúc mùa lễ Tết Nguyên Đán và Nguyên Tiêu. Nguyên rằm tháng giêng bắt nguồn từ hoạt động của Phật Giáo, do vào ngày này chư Tăng tập trung đông đủ để nghe Phật thuyết pháp, nên những người theo đạo Phật dùng ngày rằm tháng giêng để tưởng nhớ và cúng dường chư Phật.Ngày lễ được bắt đầu từ giữa đêm 14 (đêm trước trăng rằm) trọn ngày 15 (ngày rằm) cho đến nửa đêm 15 (đêm trăng rằm).',
    price:'150000',
    url1:'imgs/Tết Nguyên Tiêu/thuongnguyen-431.JPG',
    url2:'imgs/Tết Nguyên Tiêu/thuongnguyen-432.JPG',
    url3:'imgs/Tết Nguyên Tiêu/thuongnguyen-433.JPG', 
    url4:'imgs/Tết Nguyên Tiêu/thuongnguyen-hight1.jpg',
    url5:'imgs/Tết Nguyên Tiêu/thuongnguyen-hight2.png',
    url6:'imgs/Tết Nguyên Tiêu/thuongnguyen-hight3.jpg'
},
{
    nameLeHoi: 'Lễ Vu Lan báo hiếu',
    tiemStart:'2018/08/25',
    timeEnd:'2018/08/26',
    diadiem: 'Việt Nam',
    kinhdo:'15.7587298',
    vido:'101.4157145',
    lucdia:'Châu Á',
    tongiao:'Đạo Phật',
    chitiet:'Lễ Vu Lan hay còn gọi là lễ báo hiếu cha mẹ rơi vào ngày 15 tháng 7 âm lịch là một trong những ngày lễ chXuất phát từ sự tích về Bồ tát Mục Kiền Liên đại hiếu đã cứu mẹ của mình ra khỏi kiếp ngạ quỷ. Vu Lan là ngày lễ hằng năm để tưởng nhớ công ơn cha mẹ (và tổ tiên nói chung) - cha mẹ của kiếp này và của các kiếp trước.Lễ Vu Lan: Nguồn gốc và ý nghĩa thờ cúng - Ảnh 1Lễ Vu Lan có nguồn gốc từ tích Mục Kiều Liên cứu mẹ. Theo kinh Vu Lan thì ngày xưa, Mục Kiền Liên đã tu luyện thành công nhiều phép thần thông. Mẹ ông là bà Thanh Đề đã qua đời, ông tưởng nhớ và muốn biết bây giờ mẹ như thế nào nên dùng mắt phép nhìn khắp trời đất để tìm. Thấy mẹ mình, vì gây nhiều nghiệp ác nên phải sanh làm ngạ quỷ, bị đói khát hành hạ khổ sở, ông đã đem cơm xuống tận cõi quỷ để dâng mẹ. Tuy nhiên do đói ăn lâu ngày nên mẹ của ông khi ăn đã dùng một tay che bát cơm của mình đi không cho các cô hồn khác đến tranh cướp, vì vậy khi thức ăn đưa lên miệng đã hóa thành lửa đỏ. Cũng theo kinh Vu-Lan-bồn, Mục Liên quay về tìm Phật để hỏi cách cứu mẹ, Phật dạy rằng: "Dù ông thần thông quảng đại đến đâu cũng không đủ sức cứu mẹ ông đâu. Chỉ có một cách nhờ hợp lực của chư tăng khắp mười phương mới mong giải cứu được. Ngày rằm tháng bảy là ngày thích hợp để cung thỉnh chư tăng, hãy sắm sửa lễ cúng vào ngày đó".Làm theo lời Phật, mẹ của Mục Liên đã được giải thoát. Phật cũng dạy rằng: chúng sanh ai muốn báo hiếu cho cha mẹ cũng theo cách này. Từ đó, ngày lễ Vu-lan ra đời.ính của Phật giáo và bắt nguồn từ phong tục Trung Quốc .',
    price:'150000',
    url1:'imgs/Lễ Vu Lan báo hiếu/vulan-431.jpg',
    url2:'imgs/Lễ Vu Lan báo hiếu/vulan-432.jpg', 
    url3:'imgs/Lễ Vu Lan báo hiếu/vulan-433.jpg', 
    url4:'imgs/Lễ Vu Lan báo hiếu/vulan-hight1.jpg',
    url5:'imgs/Lễ Vu Lan báo hiếu/vulan-hight2.jpg',
    url6:'imgs/Lễ Vu Lan báo hiếu/vulan-hight3.jpg'
}
];